### PR TITLE
🎉 mkdocs website

### PR DESCRIPTION
**Pull request by jmfayard**
If merged this PR adds a basic documentation website for splitties

For some reason https://louiscad.github.io/Splitties/ does not work

But  https://jmfayard.github.io/Splitties/ does work

Maybe it's a DNS propagation issue.

There are warnings to fix - relative paths - see file `docs/warnings.txt`

### CODE REVIEW

**Comment by LouisCAD** [comment]
Thank you for the PR!
I'd not put the doc of Splitties 2 on the website because it's no longer maintained, and you need AndroidX to be compatible with modern Android which is now required to publish new apps on the Play Store, and updates too in a few days.

People can still browse the old repo tag to see historical docs if they really need it.

**Comment by LouisCAD** [comment]
The GitHub pages don't work because it's disabled in the settings of the repo. I'll take care of changing this once the website is ready enough.

**Comment by jmfayard** [comment]
@LouisCAD I see. I think you should still keep the Splitties documentation in a folder called `3` for when you launch Splitties 4. As I said, I don't plan to work further on this pull request because of the crazy month I have ahead - moving out, finding a flat in Paris and starting a new job.

**Comment by LouisCAD** [comment]
Superseded by #273
Thanks for the PR nonetheless @jmfayard, it was helpful to be able to look at some parts of it while getting more familiar with MKDocs and Material for MKDocs.

**Pull request closed without merging**
